// automatically generated by the FlatBuffers compiler, do not modify

package com.daniel.FitTrackerApp;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Splits extends Table {
  public static Splits getRootAsSplits(ByteBuffer _bb) { return getRootAsSplits(_bb, new Splits()); }
  public static Splits getRootAsSplits(ByteBuffer _bb, Splits obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Splits __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Split splits(int j) { return splits(new Split(), j); }
  public Split splits(Split obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 24, bb) : null; }
  public int splitsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createSplits(FlatBufferBuilder builder,
      int splitsOffset) {
    builder.startObject(1);
    Splits.addSplits(builder, splitsOffset);
    return Splits.endSplits(builder);
  }

  public static void startSplits(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSplits(FlatBufferBuilder builder, int splitsOffset) { builder.addOffset(0, splitsOffset, 0); }
  public static void startSplitsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(24, numElems, 8); }
  public static int endSplits(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

