// automatically generated by the FlatBuffers compiler, do not modify

package com.daniel.FitTrackerApp;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SportActivitiesWithOwner extends Table {
  public static SportActivitiesWithOwner getRootAsSportActivitiesWithOwner(ByteBuffer _bb) { return getRootAsSportActivitiesWithOwner(_bb, new SportActivitiesWithOwner()); }
  public static SportActivitiesWithOwner getRootAsSportActivitiesWithOwner(ByteBuffer _bb, SportActivitiesWithOwner obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SportActivitiesWithOwner __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SportActivityWithOwner sportActivities(int j) { return sportActivities(new SportActivityWithOwner(), j); }
  public SportActivityWithOwner sportActivities(SportActivityWithOwner obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int sportActivitiesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createSportActivitiesWithOwner(FlatBufferBuilder builder,
      int sportActivitiesOffset) {
    builder.startObject(1);
    SportActivitiesWithOwner.addSportActivities(builder, sportActivitiesOffset);
    return SportActivitiesWithOwner.endSportActivitiesWithOwner(builder);
  }

  public static void startSportActivitiesWithOwner(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSportActivities(FlatBufferBuilder builder, int sportActivitiesOffset) { builder.addOffset(0, sportActivitiesOffset, 0); }
  public static int createSportActivitiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSportActivitiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSportActivitiesWithOwner(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

