// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SportActivityMap extends Table {
  public static SportActivityMap getRootAsSportActivityMap(ByteBuffer _bb) { return getRootAsSportActivityMap(_bb, new SportActivityMap()); }
  public static SportActivityMap getRootAsSportActivityMap(ByteBuffer _bb, SportActivityMap obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SportActivityMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Polyline polyline(int j) { return polyline(new Polyline(), j); }
  public Polyline polyline(Polyline obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int polylineLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public Markers markers(int j) { return markers(new Markers(), j); }
  public Markers markers(Markers obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 24, bb) : null; }
  public int markersLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createSportActivityMap(FlatBufferBuilder builder,
      int polylineOffset,
      int markersOffset) {
    builder.startObject(2);
    SportActivityMap.addMarkers(builder, markersOffset);
    SportActivityMap.addPolyline(builder, polylineOffset);
    return SportActivityMap.endSportActivityMap(builder);
  }

  public static void startSportActivityMap(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPolyline(FlatBufferBuilder builder, int polylineOffset) { builder.addOffset(0, polylineOffset, 0); }
  public static void startPolylineVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addMarkers(FlatBufferBuilder builder, int markersOffset) { builder.addOffset(1, markersOffset, 0); }
  public static void startMarkersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(24, numElems, 8); }
  public static int endSportActivityMap(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

