// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SportActivityWithOwner extends Table {
  public static SportActivityWithOwner getRootAsSportActivityWithOwner(ByteBuffer _bb) { return getRootAsSportActivityWithOwner(_bb, new SportActivityWithOwner()); }
  public static SportActivityWithOwner getRootAsSportActivityWithOwner(ByteBuffer _bb, SportActivityWithOwner obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SportActivityWithOwner __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String activityId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer activityIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String userId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public byte profilePic(int j) { int o = __offset(10); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int profilePicLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer profilePicAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public Polyline startPoint() { return startPoint(new Polyline()); }
  public Polyline startPoint(Polyline obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String activity() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer activityAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public double distance() { int o = __offset(16); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public long duration() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long startTimestamp() { int o = __offset(20); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long endTimestamp() { int o = __offset(22); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long steps() { int o = __offset(24); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static void startSportActivityWithOwner(FlatBufferBuilder builder) { builder.startObject(11); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addActivityId(FlatBufferBuilder builder, int activityIdOffset) { builder.addOffset(1, activityIdOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(2, userIdOffset, 0); }
  public static void addProfilePic(FlatBufferBuilder builder, int profilePicOffset) { builder.addOffset(3, profilePicOffset, 0); }
  public static int createProfilePicVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startProfilePicVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addStartPoint(FlatBufferBuilder builder, int startPointOffset) { builder.addStruct(4, startPointOffset, 0); }
  public static void addActivity(FlatBufferBuilder builder, int activityOffset) { builder.addOffset(5, activityOffset, 0); }
  public static void addDistance(FlatBufferBuilder builder, double distance) { builder.addDouble(6, distance, 0.0); }
  public static void addDuration(FlatBufferBuilder builder, long duration) { builder.addLong(7, duration, 0L); }
  public static void addStartTimestamp(FlatBufferBuilder builder, long startTimestamp) { builder.addLong(8, startTimestamp, 0L); }
  public static void addEndTimestamp(FlatBufferBuilder builder, long endTimestamp) { builder.addLong(9, endTimestamp, 0L); }
  public static void addSteps(FlatBufferBuilder builder, long steps) { builder.addLong(10, steps, 0L); }
  public static int endSportActivityWithOwner(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

